lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 21600  # in seconds, 21600 seconds = 6 hours
    # user_identity_field: email
    api_platform:
        check_path: /authentication_token
        username_path: email
        password_path: password